### ISSUE TITLE
Unread count when more than 1000 items are unread

### ISSUE THREAD

**Issue by ranbarton** [godenzim/readernotifier#1]
Years ago, when Reader Notifier was first under development, I exchanged emails with the author showing him a Firefox extension that obtained an accurate count of unread items above 1000. He adopted this code and it worked great for years. Recently, the old versions stopped working, and Google led me here. Thank you for helping to modernize this app.

I note that it cannot count above 1000 unread items anymore. Is this a Google-imposed limitation, or would this perhaps be something that could be fixed, by any chance?

Either way, my thanks for keeping this alive.

**Comment by godenzim** [comment]
This is a Google-imposed limitation, in fact the call to the server to get the unread count cannot return a number above 1000 (I am not sure why but that is the way it is).

**Comment by ranbarton** [comment]
Many, many Google Reader clients act like this is the case, but there are a few that seem to get around it. E.g., the Google Reader Unred Count extension https://chrome.google.com/extensions/detail/gadjnepdmkddlhhdofmbbojakdokepel

It shows me 2773 and not 1000+ when I am in Greader.

My sincere thanks for keeping this utility current for Mac users.

**Comment by godenzim** [comment]
it seems to me that one way to get around it is to actually keep downloading all the feeds and then count them (and I'm not sure I want to do that), or maybe there is another way, if only the google API was actually documented... I can do some research around, but I cannot promise anything.
